[versions]
detektPlugin = "1.23.8"
kotlinPlugin = "2.2.21"

clikt = "5.0.3"
kotest = "6.0.5"

[libraries]
# These are Maven coordinates for Gradle plugins, which are required for use in precompiled plugin scripts.
plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektPlugin" }
plugin-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detektPlugin" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinPlugin" }

clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
